name: TypeScript CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # pin@v4.1.0
        with:
          version: 9.1.1
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4.4.0
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'examples/frontend/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
